[sdl]
autolock=false

[dosbox]
machine=svga_s3
memsize=16

[render]
frameskip=0
aspect=false
scaler=none

[cpu]
core=auto
cputype=auto
cycles=auto

[mixer]
nosound=false
rate=44100

[autoexec]
@echo off
mount c .
c:
cls
echo Microsoft(R) MS-DOS 6.22 / YFGeek Edition
echo DOSBox x86 emulator is running locally in your browser.
echo.
echo Type MARIO to run MARIO.EXE.
echo Type DIR to inspect the virtual C drive.
echo.
